
_KNOW THIS PROCESS_ BY HEART


Apache php correct setup.

https://cwiki.apache.org/confluence/display/HTTPD/php

* Apache PHP discussion on opening multiple processes.

installation uses prefork (as you can see in the apachectl -V
output). This mpm spawns a process per request. So if you are under a
bit of load and nowadays knowing how many concurrent requests some
browsers send, that list of process is quite usual.  All this make
apache crawl and suffer from the load your php scripts cause, making
Apache look as it is not performing well, when it is all due to php
parsing and unperformant php scripts.  Now, what should you do to
avoid this?  Relief Apache from the burden of mod_php, move your php
parsing to php-fpm, that will allow you to use Apache HTTPD's "event"
mpm, that would even allow you to have 1 process with a thousand
threads if you want, and not only that, it is quite more responsive to
load spikes and will be as cool and fast as any other http server out
there. And most importantly, Apache processes won't be stuck in the
hundreds.


* flexbox

- PRIMARY PROPERTIES

 display: flex

 flex-direction: (row, column, row-reverse, column-reverse)
 justify-content: (flex-start, center, flex-end, space-between, space-around)
 align-item: (stretch, flex-start, flex-end, center)
 flex-wrap: (wrap)

defaults;

* media queries example
@media(min-width: 600px)
{
 .container {

   flex-direction: row;
   justify-content: space-around;
   align-items: center;
 }
}

* resources
css-tricks the complete guide to flexbox.
mdn flexbox
wes bos
